"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "/"
"preserve_hierarchy": true
"base_url": "https://api.crowdin.com"

"files": [
  {
    "source": "/MinecraftClient/Resources/Translations/Translations.resx",
    "translation": "/MinecraftClient/Resources/Translations/Translations.%osx_code%.resx"
  }
]
